#%RAML 1.0 DataType

description: A shipping destination address for a fulfillment method
type: object
properties:
  id:
    type: string
    required: true
    description: Unique identifier for this destination address
    example: "addr_1"
  address_locality:
    type: string
    required: false
    description: City or locality of the destination
    example: "Antioch"
  address_region:
    type: string
    required: false
    description: State or region of the destination
    example: "CA"
  postal_code:
    type: string
    required: false
    description: Postal/ZIP code of the destination
    example: "94509"
  address_country:
    type: string
    required: true
    description: ISO 3166-1 alpha-2 country code of the destination
    example: "US"
