#%RAML 1.0 DataType

description: Reference to a catalog item by its unique ID
type: object
properties:
  id:
    type: string
    required: true
    description: Unique identifier of the catalog item
    example: "WH1000XM5-BLK"
