#%RAML 1.0 DataType
displayName: UpdateItem
description: Product item reference used in a PUT cart line item
type: object
properties:
  id:
    type: string
    description: Unique product identifier / SKU
    minLength: 1
    example: WH1000XM5-BLK
